all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    
    environments:
      children:
        dev:
          hosts:
            localhost:
              ansible_connection: local
              env_name: dev
              terraform_workspace: dev
        
        staging:
          hosts:
            localhost:
              ansible_connection: local
              env_name: staging
              terraform_workspace: staging
        
        prod:
          hosts:
            localhost:
              ansible_connection: local
              env_name: prod
              terraform_workspace: prod
